// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vabispklp/yap/internal/app/storage (interfaces: StorageExpected)

// Package storage_mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/vabispklp/yap/internal/app/model"
)

// MockStorageExpected is a mock of StorageExpected interface.
type MockStorageExpected struct {
	ctrl     *gomock.Controller
	recorder *MockStorageExpectedMockRecorder
}

// MockStorageExpectedMockRecorder is the mock recorder for MockStorageExpected.
type MockStorageExpectedMockRecorder struct {
	mock *MockStorageExpected
}

// NewMockStorageExpected creates a new mock instance.
func NewMockStorageExpected(ctrl *gomock.Controller) *MockStorageExpected {
	mock := &MockStorageExpected{ctrl: ctrl}
	mock.recorder = &MockStorageExpectedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageExpected) EXPECT() *MockStorageExpectedMockRecorder {
	return m.recorder
}

// AddRedirectLink mocks base method.
func (m *MockStorageExpected) AddRedirectLink(arg0 context.Context, arg1 model.ShortURL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRedirectLink", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddRedirectLink indicates an expected call of AddRedirectLink.
func (mr *MockStorageExpectedMockRecorder) AddRedirectLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRedirectLink", reflect.TypeOf((*MockStorageExpected)(nil).AddRedirectLink), arg0, arg1)
}

// GetRedirectLink mocks base method.
func (m *MockStorageExpected) GetRedirectLink(arg0 context.Context, arg1 string) (*model.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRedirectLink", arg0, arg1)
	ret0, _ := ret[0].(*model.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRedirectLink indicates an expected call of GetRedirectLink.
func (mr *MockStorageExpectedMockRecorder) GetRedirectLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRedirectLink", reflect.TypeOf((*MockStorageExpected)(nil).GetRedirectLink), arg0, arg1)
}
